# --- !Ups

ALTER TABLE licenciamento.tipo_documento ADD COLUMN tipo_analise integer;
COMMENT ON COLUMN licenciamento.tipo_documento.tipo_analise IS 'Indica se o documento será avaliado na análise técnica ou análise jurídica (0 - Jurídica; 1 - Técnica).';

UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 101 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 102 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 103 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 104 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 105 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 106 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 107 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 108 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 109 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 110 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 111 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 112 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 113 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 114 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 115 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 116 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 117 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 118 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 119 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 120 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 121 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 122 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 123 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 124 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 125 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 126 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 127 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 128 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 129 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 130 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 131 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 132 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 133 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 134 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 135 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 136 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 137 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 138 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 139 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 140 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 141 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 142 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 143 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 144 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 145 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 146 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 147 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 148 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 149 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 150 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 151 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 152 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 153 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 154 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 155 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 156 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 157 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 158 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 159 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 160 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 161 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 162 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 163 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 164 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 165 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 166 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 168 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 169 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 170 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 171 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 172 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 173 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 174 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 175 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 0 WHERE id= 177 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 178 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 179 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 180 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 181 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 182 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 183 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 184 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 186 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 187 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 188 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 189 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 190 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 191 ;
UPDATE licenciamento.tipo_documento SET tipo_analise= 1 WHERE id= 192 ;

# --- !Downs

ALTER TABLE licenciamento.tipo_documento DROP COLUMN tipo_analise;
