package security;


public enum Acao {

	LISTAR_PROCESSO_JURIDICO,
	VINCULAR_PROCESSO_JURIDICO,
	CONSULTAR_PROCESSO,
	VALIDAR_PARECER_JURIDICO,
	VINCULAR_PROCESSO_TECNICO,
	INICIAR_PARECER_JURIDICO,
	INICIAR_PARECER_TECNICO,
	APROVAR_ANALISE,
	VALIDAR_PARECER_TECNICO,
	VALIDAR_PARECERES_JURIDICO_TECNICO,
	CONSULTAR_LICENCAS_EMITIDAS,
	SUSPENDER_LICENCA_EMITIDA,
	CANCELAR_LICENCA_EMITIDA,
	LISTAR_PROCESSOS_MANEJO,
	ANALIZAR_PROCESSO_MANEJO,
	VISUALIZAR_PROCESSO_MANEJO
}
