package security;


public enum Acao {

	LISTAR_PROCESSO("ANL_LISTAR_PROCESSO"),
	VINCULAR_PROCESSO("ANL_VINCULAR_PROCESSO"),
	VINCULAR_PROCESSO_JURIDICO("ANL_VINCULAR_PROCESSO_JURIDICO"),
	CONSULTAR_PROCESSO("ANL_CONSULTAR_PROCESSO"),
	VALIDAR_PARECER_JURIDICO("ANL_VALIDAR_PARECER_JURIDICO"),
	VINCULAR_PROCESSO_TECNICO("ANL_VINCULAR_PROCESSO_TECNICO"),
	INICIAR_PARECER_JURIDICO("ANL_INICIAR_PARECER_JURIDICO"),
	INICIAR_PARECER_TECNICO("ANL_INICIAR_PARECER_TECNICO"),
	APROVAR_ANALISE("ANL_APROVAR_ANALISE"),
	VALIDAR_PARECER_TECNICO("ANL_VALIDAR_PARECER_TECNICO"),
	VALIDAR_PARECERES_JURIDICO_TECNICO("ANL_VALIDAR_PARECERES_JURIDICO_TECNICO"),
	CONSULTAR_LICENCAS_EMITIDAS("ANL_CONSULTAR_LICENCAS_EMITIDAS"),
	SUSPENDER_LICENCA_EMITIDA("ANL_SUSPENDER_LICENCA_EMITIDA"),
	CANCELAR_LICENCA_EMITIDA("ANL_CANCELAR_LICENCA_EMITIDA"),
	LISTAR_PROCESSO_MANEJO("ANL_LISTAR_PROCESSO_MANEJO"),
	ANALISAR_PROCESSO_MANEJO("ANL_ANALISAR_PROCESSO_MANEJO"),
	VISUALIZAR_PROCESSO_MANEJO("ANL_VISUALIZAR_PROCESSO_MANEJO"),
	CADASTRAR_PROCESSO_MANEJO("ANL_CADASTRAR_PROCESSO_MANEJO");

	public String codigo;

	private Acao(String codigo) {

		this.codigo = codigo;
	}
}
