var disabledFilterFields = {
    SITUACAO: 'SITUACAO',
    PERIODO_PROCESSO: 'PERIODO_PROCESSO',
    ANALISTA_TECNICO: 'ANALISTA_TECNICO',
    GERENCIA: 'GERENCIA'
};

exports.DISABLED_FILTER_FIELDS = disabledFilterFields;