package serializers;

import flexjson.JSONSerializer;
import utils.SerializerUtil;

public class AnalisesManejoSerializer {

	public static JSONSerializer findById = SerializerUtil.create(
			"id",
			"dataAnalise",
			"pathAnexo",
			"analiseTemporal",
			"areaManejoFlorestalSolicitada",
			"areaPreservacaoPermanente",
			"areaServidao",
			"areaAntropizadaNaoConsolidada",
			"areaUsoRestrito",
			"areaSemPotencial",
			"areaCorposAgua",
			"areaEmbargadaIbama",
			"areaEmbargadaLdi",
			"areaSeletivaNdfi",
			"areaEfetivoNdfi",
			"areaExploracaoNdfiBaixo",
			"areaExploracaoNdfiMedio",
			"areaSemPreviaExploracao",
			"consideracoes",
			"conclusao",
			"processoManejo.numeroProcesso",
			"processoManejo.cpfCnpj",
			"processoManejo.denominacaoEmpreendimentoSimlam",
			"processoManejo.nomeMunicipioSimlam",
			"analisesNdfi.id",
			"analisesNdfi.dataAnalise",
			"analisesNdfi.orbita",
			"analisesNdfi.ponto",
			"analisesNdfi.satelite",
			"analisesNdfi.nivelExploracao",
			"analisesNdfi.valor",
			"analisesNdfi.area",
			"analisesVetorial.id",
			"analisesVetorial.tipo",
			"analisesVetorial.nome",
			"analisesVetorial.distanciaPropriedade",
			"analisesVetorial.sobreposicaoPropriedade",
			"analisesVetorial.distanciaAmf",
			"analisesVetorial.sobreposicaoAmf",
			"analisesVetorial.observacao",
			"basesVetorial.id",
			"basesVetorial.nome",
			"basesVetorial.fonte",
			"basesVetorial.ultimaAtualizacao",
			"basesVetorial.escala",
			"basesVetorial.observacao",
			"observacoesDadosImovel",
			"observacoesBaseVetorial",
			"observacoesAnaliseVetorial",
			"observacoesAnaliseTemporal",
			"observacoesInsumosUtilizados",
			"observacoesCalculoNDFI",
			"observacoesCalculoAreaEfetiva",
			"observacoesDetalhamentoAreaEfetiva",
			"observacoesConsideracoes",
			"observacoesConclusao"
	);
}
