package serializers;

import java.util.Date;

import flexjson.JSONSerializer;
import utils.SerializerUtil;

public class ProcessoSerializer {
	
	public static JSONSerializer list = SerializerUtil.create(
			"id",
			"numero",
			"empreendimento.pessoa.cpf",
			"empreendimento.nome");
	
	public static JSONSerializer getInfo = SerializerUtil.create(
			"processo.id",
			"processo.numero",
			"processo.analises.id",
			"processo.analises.dataCadastro",
			"processo.analises.dataVencimentoPrazo",
			"processo.analises.analiseJuridica",
			"processo.empreendimento.id",
			"processo.empreendimento.denominacao",
			"processo.empreendimento.jurisdicao",
			"processo.empreendimento.municipio.nome",
			"processo.empreendimento.municipio.estado.codigo",
			"processo.empreendimento.municipio.id",
			"processo.empreendimento.contato.email",
			"processo.empreendimento.contato.telefone",
			"processo.empreendimento.contato.celular",
			"processo.empreendimento.enderecoCorrespondencia.logradouro",
			"processo.empreendimento.enderecoCorrespondencia.numero",
			"processo.empreendimento.enderecoCorrespondencia.cep",
			"processo.empreendimento.enderecoCorrespondencia.complemento",
			"processo.empreendimento.enderecoCorrespondencia.bairro",
			"processo.empreendimento.enderecoCorrespondencia.correspondencia",
			"processo.empreendimento.enderecoCorrespondencia.caixaPostal",
			"processo.empreendimento.enderecoCorrespondencia.municipio.nome",
			"processo.empreendimento.enderecoCorrespondencia.municipio.estado.codigo",
			"processo.empreendimento.enderecoCorrespondencia.roteiroAcesso",
			"processo.empreendimento.enderecoCorrespondencia.tipo",
			"processo.empreendimento.proprietarios.pessoa.cpf",
			"processo.empreendimento.proprietarios.pessoa.nome",
			"processo.empreendimento.proprietarios.pessoa.dataNascimento",
			"processo.empreendimento.proprietarios.pessoa.rg",
			"processo.empreendimento.localizacao",
			"processo.empreendimento.imovel.codigo",
			"processo.empreendimento.imovel.nome",
			"processo.empreendimento.imovel.municipio.nome",
			"processo.empreendimento.imovel.municipio.estado.nome",
			"processo.empreendimento.coordenadas",
			"processo.empreendimento.responsaveis.pessoa.cpf",
			"processo.empreendimento.responsaveis.pessoa.nome",
			"processo.empreendimento.responsaveis.contato.email",
			"processo.empreendimento.responsaveis.contato.celular",
			"processo.empreendimento.pessoa.type",
			"processo.empreendimento.pessoa.cpf",
			"processo.empreendimento.pessoa.nome",
			"processo.empreendimento.pessoa.nomeMae",
			"processo.empreendimento.pessoa.rg",
			"processo.empreendimento.pessoa.municipioNascimento.nome",
			"processo.empreendimento.pessoa.municipioNascimento.estado.codigo",
			"processo.empreendimento.pessoa.dataNascimento",
			"processo.empreendimento.pessoa.sexo",
			"processo.empreendimento.pessoa.estadoCivil.nome",
			"processo.empreendimento.pessoa.tituloEleitor",
			"processo.empreendimento.pessoa.cnpj",
			"processo.empreendimento.pessoa.razaoSocial",
			"processo.empreendimento.pessoa.nomeFantasia",
			"processo.empreendimento.pessoa.municipio.nome",
			"processo.empreendimento.pessoa.municipio.estado.codigo",
			"processo.empreendimento.pessoa.isento",
			"processo.empreendimento.pessoa.inscricaoEstadual",
			"processo.empreendimento.pessoa.dataFundacao",
			"processo.empreendimento.empreendedor.esfera",
			"processo.empreendimento.empreendedor.representantesLegais.pessoa.cpf",
			"processo.empreendimento.empreendedor.representantesLegais.pessoa.nome",
			"processo.empreendimento.empreendedor.representantesLegais.pessoa.contato.email",
			"processo.empreendimento.empreendedor.representantesLegais.dataVinculacao",
			"processo.empreendimento.empreendedor.pessoa.type",
			"processo.empreendimento.empreendedor.pessoa.cpf",
			"processo.empreendimento.empreendedor.pessoa.nome",
			"processo.empreendimento.empreendedor.pessoa.nomeMae",
			"processo.empreendimento.empreendedor.pessoa.rg",
			"processo.empreendimento.empreendedor.pessoa.municipioNascimento.nome",
			"processo.empreendimento.empreendedor.pessoa.municipioNascimento.estado.codigo",
			"processo.empreendimento.empreendedor.pessoa.dataNascimento",
			"processo.empreendimento.empreendedor.pessoa.sexo",
			"processo.empreendimento.empreendedor.pessoa.estadoCivil.nome",
			"processo.empreendimento.empreendedor.pessoa.tituloEleitor",
			"processo.empreendimento.empreendedor.pessoa.cnpj",
			"processo.empreendimento.empreendedor.pessoa.dataFundacao",
			"processo.empreendimento.empreendedor.pessoa.razaoSocial",
			"processo.empreendimento.empreendedor.pessoa.nomeFantasia",
			"processo.empreendimento.empreendedor.pessoa.municipio.nome",
			"processo.empreendimento.empreendedor.pessoa.municipio.estado.codigo",
			"processo.empreendimento.empreendedor.pessoa.isento",
			"processo.empreendimento.empreendedor.pessoa.inscricaoEstadual",
			"processo.empreendimento.empreendedor.pessoa.contato.email",
			"processo.empreendimento.empreendedor.pessoa.contato.telefone",
			"processo.empreendimento.empreendedor.pessoa.contato.celular",
			"processo.empreendimento.empreendedor.pessoa.enderecos.logradouro",
			"processo.empreendimento.empreendedor.pessoa.enderecos.numero",
			"processo.empreendimento.empreendedor.pessoa.enderecos.complemento",
			"processo.empreendimento.empreendedor.pessoa.enderecos.bairro",
			"processo.empreendimento.empreendedor.pessoa.enderecos.correspondencia",
			"processo.empreendimento.empreendedor.pessoa.enderecos.cep",
			"processo.empreendimento.empreendedor.pessoa.enderecos.caixaPostal",
			"processo.empreendimento.empreendedor.pessoa.enderecos.municipio.nome",
			"processo.empreendimento.empreendedor.pessoa.enderecos.municipio.estado.codigo",
			"processo.empreendimento.empreendedor.pessoa.enderecos.roteiroAcesso",
			"processo.empreendimento.empreendedor.pessoa.enderecos.tipo",
			"processo.caracterizacao.solicitacoesDocumento.documento.id",
			"processo.caracterizacao.solicitacoesDocumento.tipoDocumento.nome");
}
