var AcaoTramitacao = {

    DEFERIR_ANALISE_GEO: 49,
	INDEFERIR_ANALISE_GEO: 50,
    NOTIFICAR_PELO_ANALISTA_GEO: 3,
    INDEFERIR_ANALISE_TECNICA_VIA_GERENTE: 13,
    SOLICITAR_DESVINCULO: 59,
    VALIDAR_PARECER_GEO_GERENTE: 63,
    SOLICITAR_AJUSTES_PARECER_GEO_PELO_GERENTE: 55,
    INVALIDAR_PARECER_GEO_ENCAMINHANDO_GEO: 58,
    AGUARDAR_RESPOSTA_COMUNICADO: 65,
    NOTIFICAR_PELO_ANALISTA_TECNICO: 66

};

exports.utils.AcaoTramitacao = AcaoTramitacao;
