var CondicaoTramitacao = {

	AGUARDANDO_VINCULACAO_JURIDICA: 1,
	AGUARDANDO_ANALISE_JURIDICA: 2,
	EM_ANALISE_JURIDICA: 3,
	NOTIFICADO: 4,
	AGUARDANDO_VALIDACAO_JURIDICA: 5,
	ARQUIVADO: 6,
	AGUARDANDO_VINCULACAO_TECNICA: 7,
	AGUARDANDO_ANALISE_TECNICA: 8,
	EM_ANALISE_TECNICA: 9,
	AGUARDANDO_VALIDACAO_TECNICA: 10

};

exports.utils.CondicaoTramitacao = CondicaoTramitacao;