var Perfis = {

	COORDENADOR_JURIDICO: 3,
	ADMINISTRATIVO_JURIDICO: 4,
	CONSULTOR_JURIDICO: 5,
	COORDENADOR_TECNICO: 6,
	GERENTE_TECNICO: 7,
	ANALISTA_TECNICO: 8,
	DIRETOR: 9
};

exports.utils.Perfis = Perfis;