var Perfis = {

	COORDENADOR_JURIDICO: "COORDENADOR_JURIDICO",
	ADMINISTRATIVO_JURIDICO: "ADMINISTRATIVO_JURIDICO",
	CONSULTOR_JURIDICO: "CONSULTOR_JURIDICO",
	COORDENADOR_TECNICO: "COORDENADOR_TECNICO",
	GERENTE_TECNICO: "GERENTE_TECNICO",
	ANALISTA_TECNICO: "ANALISTA_TECNICO",
	APROVADOR: "APROVADOR",
	ANALISTA_SIMLAM: "ANALISTA_SIMLAM",
	PROTOCOLO: "PROTOCOLO"
};

exports.utils.Perfis = Perfis;