var TiposUpload = {

    PARECER_ANALISE_GEO: 'PARECER',
    NOTIFICACAO: 'NOTIFICACAO',
    DOCUMENTO_ANALISE_TEMPORAL: 'DOCUMENTO_ANALISE_TEMPORAL',
    PARECER_ANALISE_TECNICA: 'PARECER_ANALISE_TECNICA'
};

exports.utils.TiposUpload = TiposUpload;
