var TiposDocumentosAnalise = {

    ANALISE_JURIDICA: 1,
    ANALISE_TECNICA: 2,
    ANALISE_GEO: 3,
    PARECER_ANALISE_TECNICA: 4,
    PARECER_ORGAO: 5,
    PARECER_ANALISE_GEO: 16,
    INCONSISTENCIA: 18,
    NOTIFICACAO: 22,
    DOCUMENTO_ANALISE_TEMPORAL:23,
    DOCUMENTO_RIT: 24,
    DOCUMENTO_VISTORIA: 25,
    INCONSISTENCIA_TECNICA:26,
    INCONSISTENCIA_VISTORIA: 27,
    PARECER_ANALISE_TECNICA: 28,
    AUTO_INFRACAO: 29,
    DOCUMENTO_RELATORIO_TECNICO_VISTORIA: 30,
    DOCUMENTO_MINUTA: 31,

};

exports.utils.TiposDocumentosAnalise = TiposDocumentosAnalise;
