var TiposDocumentosAnalise = {

    ANALISE_JURIDICA: 1,
    ANALISE_TECNICA: 2,
    ANALISE_GEO: 3,
    INCONSISTENCIA: 4,
    PARECER_ORGAO: 5,
    PARECER_ANALISE_GEO: 16,
    NOTIFICACAO: 22,
    DOCUMENTO_ANALISE_TEMPORAL:23,
    DOCUMENTO_RIT: 24,
    DOCUMENTO_VISTORIA: 25,
    INCONSISTENCIA_VISTORIA: 27,
    PARECER_ANALISE_TECNICA: 28
};

exports.utils.TiposDocumentosAnalise = TiposDocumentosAnalise;
