package enums;

import java.util.Arrays;
import java.util.List;

import static models.tramitacao.AcaoTramitacao.*;

public enum PerfilAcoesEnum {

	ANALISTA_GEO,
	COORDENADOR,
	ANALISTA_TECNICO;

	public List<Long> getAcoesHistoricoTramitacao() {

		if(this.equals(ANALISTA_GEO)) {

			return Arrays.asList(NOTIFICAR_PELO_ANALISTA_GEO,
					DEFERIR_ANALISE_GEO_VIA_COORDENADOR,
					INDEFERIR_ANALISE_GEO_VIA_COORDENADOR,
					INICIAR_ANALISE_GEO,
					SOLICITAR_DESVINCULO_ANALISE_GEO,
					SOLICITAR_AJUSTES_PARECER_GEO_PELO_COORDENADOR);

		} else if(this.equals(COORDENADOR)) {

			return Arrays.asList(NOTIFICAR_PELO_ANALISTA_GEO,
					DEFERIR_ANALISE_GEO_VIA_COORDENADOR,
					INDEFERIR_ANALISE_GEO_VIA_COORDENADOR,
					INICIAR_ANALISE_GEO,
					SOLICITAR_DESVINCULO_ANALISE_GEO,
					SOLICITAR_DESVINCULO_ANALISE_TECNICA,
					VINCULAR_ANALISTA,
					INICIAR_ANALISE_TECNICA,
					INVALIDAR_PARECER_GEO_PELO_COORDENADOR,
					VALIDAR_DEFERIMENTO_GEO_PELO_COORDENADOR,
					VALIDAR_INDEFERIMENTO_GEO_PELO_COORDENADOR,
					SOLICITAR_AJUSTES_PARECER_GEO_PELO_COORDENADOR,
					INVALIDAR_PARECER_GEO_ENCAMINHANDO_GEO,
					INICIAR_ANALISE_COORDENADOR,
					VALIDAR_PARECER_GEO_COORDENADOR,
					NOTIFICAR_PELO_ANALISTA_TECNICO);

		}

		return Arrays.asList(VALIDAR_PARECER_GEO_COORDENADOR, INICIAR_ANALISE_TECNICA);

	}

}
