package enums;

import java.util.Arrays;
import java.util.List;

import static models.tramitacao.AcaoTramitacao.*;

public enum PerfilAcoesEnum {

	ANALISTA_GEO,
	GERENTE,
	ANALISTA_TECNICO;

	public List<Long> getAcoesHistoricoTramitacao() {

		if(this.equals(ANALISTA_GEO)) {

			return Arrays.asList(NOTIFICAR_PELO_ANALISTA_GEO,
					DEFERIR_ANALISE_GEO_VIA_GERENTE,
					INDEFERIR_ANALISE_GEO_VIA_GERENTE,
					INICIAR_ANALISE_GEO,
					SOLICITAR_DESVINCULO,
					SOLICITAR_AJUSTES_PARECER_GEO_PELO_GERENTE);

		} else if(this.equals(GERENTE)) {

			return Arrays.asList(NOTIFICAR_PELO_ANALISTA_GEO,
					DEFERIR_ANALISE_GEO_VIA_GERENTE,
					INDEFERIR_ANALISE_GEO_VIA_GERENTE,
					INICIAR_ANALISE_GEO,
					SOLICITAR_DESVINCULO,
					VINCULAR_ANALISTA,
					INICIAR_ANALISE_TECNICA,
					INVALIDAR_PARECER_GEO_PELO_GERENTE,
					VALIDAR_DEFERIMENTO_GEO_PELO_GERENTE,
					VALIDAR_INDEFERIMENTO_GEO_PELO_GERENTE,
					SOLICITAR_AJUSTES_PARECER_GEO_PELO_GERENTE,
					INVALIDAR_PARECER_GEO_ENCAMINHANDO_GEO,
					INICIAR_ANALISE_GERENTE,
					VALIDAR_PARECER_GEO_GERENTE,
					NOTIFICAR_PELO_ANALISTA_TECNICO);

		}

		return Arrays.asList(VALIDAR_PARECER_GEO_GERENTE, INICIAR_ANALISE_TECNICA);

	}

}
